<h1>About Medea Labs</h1>
<div>
<h3>A Community For Creatives</h3>
<p>Medea Labs aims to be a place where creative people can share their ideas for all types of media. As a virtual community of creative people, the Medea Labs website and mobile app will allow users to display selections from their portfolio of work, and share their ideas for projects ranging from photography or digital art to programming. The Medea Labs app will feature user portfolios and idea post. The app will tie into the Twitter API so that users can easily share links to their posts with the Twitter community.</p>
</div>
<div>
<h3>Terms of Service</h3>
<p>This will be replaced with actual terms of service currently being hammered out. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Etiam porta sem malesuada magna mollis euismod. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>

<p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum. Etiam porta sem malesuada magna mollis euismod. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Cras mattis consectetur purus sit amet fermentum.</p>
</div>

<div>
<h3>Reporting Abuse</h3>
<p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Etiam porta sem malesuada magna mollis euismod. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
<p>
<a class="btn btn-info" href="contact.php">Report Abuse</a>
</p>

</div>