<h1>About Medea Labs</h1>
<div>
<h3>A Community For Creatives</h3>
<p>Medea Labs aims to be a place where creative people can share their ideas for all types of media. As a virtual community of creative people, the Medea Labs website and mobile app will allow users to display selections from their portfolio of work, and share their ideas for projects ranging from photography or digital art to programming. The Medea Labs app will feature user portfolios and idea post. The app will tie into the Twitter API so that users can easily share links to their posts with the Twitter community.</p>
</div>
<div>
<h3>Terms of Service</h3>
<p>The Terms of Service are simple: Be kind to all, don't raise a ruckus, and keep the content 'family-friendly'! Our grandmothers use this site and if you upset Mamaw, we will certainly hear about it, and you'll be in trouble. The administrators reserve the right to remove content as they see fit, however the offending post in question will be reviewed, and poster can dispute the removal. If it was all a silly misunderstanding the content will be returned to its original condition.</p>

<p>The goal of Medea Labs is to share images and ideas that are interesting, thought provoking, and enhance our users lives in some way. Please share content with that goal in mind.</p>
</div>

<div>
<h3>Reporting Abuse</h3>
<p>If you feel you've seen something of a questionable nature on Medea Labs, please do not hesistate to report it. We will review your claim and take the necessary actions. Just hit the 'report abuse' button!</p>
<p>
<a class="btn btn-info" href="contact.php">Report Abuse</a>
</p>

</div>