<?php 


?>
<div class="page-header">
<h1>Detail View</h1>
</div>

<h2><small>Some Item Detail Info</small></h2>

<p>Project description here. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Curabitur blandit tempus porttitor. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras justo odio, dapibus ac facilisis in, egestas eget quam.</p>