<!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
        <div class="hidden-phone"><img class="pull-left" src="img/logo.png" alt="Media Labs Logo" /></div>
        <h1>Media + Ideas</h1>
        <p>A virtual community of creative people sharing their portfolios and ideas for projects ranging from photography or digital art to programming. Join today and grow your ideas!</p>
        <p class="visible-phone"><a href="signup.php" class="btn btn-warning">Sign Up &raquo;</a></p>
        <p class="hidden-phone"><a href="signup.php" class="btn btn-warning btn-large">Sign Up &raquo;</a></p>
      </div>

      <!-- dynamically generated content -->
      <div class="row">
        <div class="span8">
          <h2>Recent Activity</h2>
          <p>This section will contain recent activity posts. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a href="#">View Details &raquo;</a></p>
        </div>
        <!-- fixed sidemenu for categories of content to view -->
        <aside>
        <div class="span4">
          <h2>Categories</h2>
          <p>A sub-menu of categories. Content to be determined by users. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper.</p>
        </div>
      </div>
      </aside>
