<form action="?" method="POST" class="form-signin">
	<h2 class="form-signin-heading">Please sign in</h2>
	<p class="muted">user: tester &bull; pw: password</p> <!-- tester login REMOVE -->
		<input type="text" name="username" id="username" class="input-block-level" placeholder="User Name">
		<input type="password"  name="password" id="password" class="input-block-level" placeholder="Password">
		
	<p class="visible-desktop">Not a registered user? <a href="register.php">Sign Up</a> today!</p>
	
	<p><button class="btn btn-warning" type="submit">Sign In</button></p>
	<p class="hidden-desktop">Not a registered user? <br /><a class="btn btn-info" href="register.php">Sign Up</a></p>
</form>