<form action="?" method="POST" class="form-signin">
	<h2 class="form-signin-heading">Please sign in</h2>
		<input type="text" name="username" id="username" class="input-block-level" placeholder="User Name">
		<input type="password"  name="password" id="password" class="input-block-level" placeholder="Password">
			<label class="checkbox">
			<input type="checkbox" value="remember-me"> Remember me
			</label>
	<p>Not a registered user? <a href="signup.php">Sign Up</a> today!</p>
	<button class="btn btn-large btn-warning" type="submit">Sign in</button>	
</form>